apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  unvalidatedValues:
    uproxyType: aws

  # You may override parts of meshconfig by uncommenting the following lines.
  meshConfig:
    ambientMesh:
      mode: DEFAULT
    defaultConfig:
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"
    defaultProviders:
      metrics:
      - prometheus
    extensionProviders:
    - name: prometheus
      prometheus: {}

  components:
    cni:
      enabled: true
    # Istio Gateway feature
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
    egressGateways:
      - name: istio-egressgateway
        enabled: false
  # Global values passed through to helm global.yaml.
  # Please keep this in sync with manifests/charts/global.yaml
  values:
    global:
      operatorManageWebhooks: false
    telemetry:
      enabled: false
      v2:
        enabled: false
