apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  hub: gcr.io/istio-testing
  tag: latest

  unvalidatedValues:
    uproxyType: gke

  # You may override parts of meshconfig by uncommenting the following lines.
  meshConfig:
    ambientMesh:
      mode: DEFAULT
    defaultProviders:
      metrics:
      - prometheus
    extensionProviders:
    - name: prometheus
      prometheus: {}

  components:
    # Istio Gateway feature
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
    egressGateways:
    - name: istio-egressgateway
      enabled: false

  # Global values passed through to helm global.yaml.
  # Please keep this in sync with manifests/charts/global.yaml
  values:
    global:
      operatorManageWebhooks: true
    telemetry:
      enabled: false
      v2:
        enabled: false
