apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  unvalidatedValues:
    uproxyType: kind

  # You may override parts of meshconfig by uncommenting the following lines.
  meshConfig:
    ambientMesh:
      mode: DEFAULT
    defaultConfig:
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"

  components:
    # Istio Gateway feature
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
    egressGateways:
    - name: istio-egressgateway
      enabled: false

#  values:
#    global:
#      operatorManageWebhooks: false
