apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: add-header
spec:
  hosts:
  - helloworld
  http:
  - headers:
      response:
        set:
          x-ambient-l7-mesh: "true"
    route:
    - destination:
        host: helloworld
