apiVersion: v1
kind: ServiceAccount
metadata:
  name: uproxy
  namespace: istio-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: uproxy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: uproxy
  template:
    metadata:
      labels:
        app: uproxy
        asm-type: proxy
    spec:
      serviceAccountName: uproxy
      initContainers:
      - name: istio-init
        image: gcr.io/landow-istio-dev/uproxy:ambient-oss
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        command:
        - sh
        - -c
        - |
          # HBONE traffic goes to HBONE port...
          iptables -t nat -A PREROUTING -p tcp --dport 15008 ! -s $INSTANCE_IP ! -d $INSTANCE_IP  -j REDIRECT --to-ports 15008
          # Special logic to handle the case where we have a remote proxy (no interception) and server (interception) on the node
          # Without this, packges from remote proxy -> server would not go through uProxy, but the response would, causing breakage.
          # This ensures the response does not go through uProxy
          iptables -t nat -A PREROUTING -m state --state NEW -p tcp --tcp-flags ACK ACK ! -s $INSTANCE_IP ! -d $INSTANCE_IP  -j ACCEPT
          # Send everything else through the "outbound" port. For now, DPv2 cannot distinguish inbound vs outbound, so we
          # do some (semi-reliable) heuristics on the outbound port to treat it as inbound, when needed. Typically inbound is
          # HBONE though.
          iptables -t nat -A PREROUTING -p tcp ! -s $INSTANCE_IP ! -d $INSTANCE_IP  -j REDIRECT --to-ports 15001
          # DPv2 won't redirect the node-local traffic for us, so we send it to a different tunnel port as a way to differentiate it.
          # Here we redirect the special "node-local tunnel (15088)" to the regular HBONE port (15008).
          # TODO: instead, we should elide the tunnel completely for node-local.
          iptables -t nat -I OUTPUT 1 -p tcp -o eth0 --dport 15088 -j REDIRECT --to-port 15008
        env:
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      containers:
      - name: istio-proxy
        image: gcr.io/landow-istio-dev/uproxy:ambient-oss
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 15021
            path: /healthz/ready
        args:
        - proxy
        - sidecar
        env:
        - name: PROXY_CONFIG
          value: '{"tracing": {"disabled": {}}}'
        - name: ISTIO_BOOTSTRAP
          value: ./var/lib/istio/envoy/uproxy_bootstrap_tmpl.json
        - name: ISTIO_META_GENERATOR
          value: "uproxy-envoy"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ISTIO_META_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        volumeMounts:
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/run/secrets/tokens
          name: istio-token
        - mountPath: /var/lib/kubelet/pki # Must match due to symlinks...
          name: kubelet-creds
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      volumes:
      - name: kubelet-creds
        hostPath:
          path: /var/lib/kubelet/pki
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              path: istio-token
              expirationSeconds: 43200
              audience: istio-ca
      - name: istiod-ca-cert
        configMap:
          name: istio-ca-root-cert
